# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bridgetowncomedy.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

exclude: [node_modules, package.json, npm-debug.log, Gruntfile.js, spec]

collections:
  event:
    output: true
    permalink: /event/:path/
  performer:
    output: true
    permalink: /performer/:path/
  show:
    output: true
    permalink: /show/:path/
  venue:
    output: true
    permalink: /show/:path/